# Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Constants

In [4]:
VOCAB_SIZE = 2500

TOKEN_SPAM_PROB_FILE = 'Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'Testing/prob-all-tokens.txt'

TEST_FEATURE_MATRIX = 'Testing/test-features.txt'
TEST_TARGET_FILE = 'Testing/test-target.txt'

# Load the Data

In [6]:
#Features
X_test = np.loadtxt(TEST_FEATURE_MATRIX, delimiter=' ')
#Target
y_test = np.loadtxt(TEST_TARGET_FILE, delimiter=' ')
#Token Probability
prob_token_spam = np.loadtxt(TOKEN_SPAM_PROB_FILE, delimiter=' ')
prob_token_ham = np.loadtxt(TOKEN_HAM_PROB_FILE, delimiter=' ')
prob_all_tokens = np.loadtxt(TOKEN_ALL_PROB_FILE, delimiter=' ')

# Calculating the Joint Probability

### The Dot Product

In [7]:
X_test.dot(prob_token_spam).shape

(1724,)

## Set the Prior

$P(Spam \, | \, X) = \frac{P(X \, | \, Spam) \, P(Spam)} {P(X)}$

In [8]:
PROB_SPAM = 0.3116

In [9]:
np.log(prob_token_spam)

array([ -4.40759754,  -5.25367234,  -4.99007478, ...,  -9.60931222,
        -8.91616504, -12.09421887])

## Joint Probability in log format

In [19]:
joint_log_spam = X_test.dot(np.log(prob_token_spam) - np.log(prob_all_tokens)) + np.log(PROB_SPAM)

In [20]:
joint_log_spam[:5]

array([24.28218201,  2.16273802, 20.59295241, 17.75699915, 20.51322915])

$P(Ham \, | \, X) = \frac{P(X \, | \, Ham) \, (1 - P(Spam))} {P(X)}$

In [21]:
joint_log_ham = X_test.dot(np.log(prob_token_ham) - np.log(prob_all_tokens)) + np.log(1 - PROB_SPAM)

In [22]:
joint_log_ham[:5]

array([-60.97225142, -11.01120773, -37.9692142 , -59.13679022,
       -53.79269416])

# Making Predictions

### Checking for the higher joint probability

$$P(Spam \, | \, X) \, > \, P(Ham \, | \, X)$$
<br>
<center><b>OR</b></center>
<br>
$$P(Spam \, | \, X) \, < \, P(Ham \, | \, X)$$

In [23]:
prediction = joint_log_spam > joint_log_ham

In [24]:
prediction[-5:]

array([ True, False, False, False, False])

### Simplify

In [25]:
joint_log_spam = X_test.dot(np.log(prob_token_spam)) + np.log(PROB_SPAM)
joint_log_ham = X_test.dot(np.log(prob_token_ham)) + np.log(1 - PROB_SPAM)

SyntaxError: unmatched ')' (<ipython-input-25-945ecb1442c6>, line 1)